name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch: # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: sofia-chahrazad

      - name: Commit & push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "update stats" || echo "no changes"
          git push